import React, { useState, useEffect, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  StatusBar,
  Dimensions,
  Linking,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { BlurView } from "expo-blur";
import { LinearGradient } from "expo-linear-gradient";
import { Ionicons, FontAwesome5, Feather } from "@expo/vector-icons";
import Animated, { FadeInUp } from "react-native-reanimated";
import { useAuth } from "../../context/AuthContext";
import apiClient from "../../api/apiClient";

const { width } = Dimensions.get("window");

/**
 * LIVE STUDENT RESULT SCREEN
 * Logic: Fetches academic data from Atlas Cloud via studentId.
 * Features: Overall Grade tracking, Subject-wise breakdown, and PDF download.
 */
const ResultScreen = () => {
  const { user } = useAuth();

  // --- States ---
  const [loading, setLoading] = useState(true);
  const [resultData, setResultData] = useState(null); // Real data starts empty

  /**
   * 1. FETCH LIVE RESULT FROM CLOUD
   */
  const fetchResult = useCallback(async () => {
    try {
      setLoading(true);
      // Backend: GET /api/student/academics/:id
      const res = await apiClient.get(`/student/academics/${user.id}`);

      // We assume the backend returns an array 'results'. We take the latest one.
      if (res.data.results && res.data.results.length > 0) {
        setResultData(res.data.results[0]);
      }
    } catch (err) {
      console.error("Result Fetch Error:", err.message);
      // No dummy fallback, will show Empty State UI
    } finally {
      setLoading(false);
    }
  }, [user.id]);

  useEffect(() => {
    fetchResult();
  }, [fetchResult]);

  /**
   * 2. DOWNLOAD PDF (AWS S3 / Atlas Link)
   */
  const handleDownload = async () => {
    if (!resultData?.marksheetUrl) {
      return Alert.alert(
        "Not Ready",
        "The digital marksheet is being generated by the office."
      );
    }

    // Open the direct link from AWS S3 or server
    const supported = await Linking.canOpenURL(resultData.marksheetUrl);
    if (supported) {
      await Linking.openURL(resultData.marksheetUrl);
    } else {
      Alert.alert("Error", "Could not open document link.");
    }
  };

  if (loading) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color="#1e40af" />
        <Text style={styles.loadingTxt}>Fetching Academic Performance...</Text>
      </View>
    );
  }

  // --- UI RENDER ---
  return (
    <View style={styles.container}>
      <StatusBar barStyle="dark-content" />

      {/* Mesh Background for consistency */}
      <View style={styles.glowIndigo} />
      <View style={styles.glowPink} />

      <SafeAreaView style={{ flex: 1 }} edges={["top"]}>
        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={styles.scroll}
        >
          {resultData ? (
            <Animated.View entering={FadeInUp.duration(800)}>
              {/* Summary Header Card */}
              <BlurView intensity={90} tint="light" style={styles.summaryCard}>
                <Text style={styles.termTxt}>
                  {resultData.examName || "Final Term Result"}
                </Text>
                <View style={styles.scoreRow}>
                  <View style={styles.scoreCircle}>
                    <Text style={styles.percentTxt}>
                      {resultData.percentage}%
                    </Text>
                    <Text style={styles.labelTxt}>Overall</Text>
                  </View>
                  <View style={styles.metaCol}>
                    <Text style={styles.gradeTxt}>
                      Grade: {resultData.grade}
                    </Text>
                    <View style={styles.statusBadge}>
                      <Text style={styles.statusTxt}>PASSED</Text>
                    </View>
                  </View>
                </View>
              </BlurView>

              {/* Detailed Marks List */}
              <Text style={styles.sectionTitle}>Performance Breakdown</Text>

              {/* Mapping real subjects if array exists in schema */}
              {resultData.subjects?.map((item, index) => (
                <BlurView
                  key={index}
                  intensity={60}
                  tint="light"
                  style={styles.subjectCard}
                >
                  <View style={styles.subIcon}>
                    <Text style={styles.subInitial}>{item.name[0]}</Text>
                  </View>
                  <View style={{ flex: 1, marginLeft: 15 }}>
                    <Text style={styles.subName}>{item.name}</Text>
                    <Text style={styles.subMarks}>
                      {item.marks} / {item.total || 100}
                    </Text>
                  </View>
                  <View style={styles.gradeBadge}>
                    <Text style={styles.itemGrade}>{item.grade || "-"}</Text>
                  </View>
                </BlurView>
              ))}

              {/* PDF Action */}
              <TouchableOpacity
                style={styles.downloadBtn}
                onPress={handleDownload}
              >
                <Ionicons
                  name="cloud-download-outline"
                  size={22}
                  color="#fff"
                />
                <Text style={styles.downloadTxt}>
                  Download Digital Marksheet
                </Text>
              </TouchableOpacity>
            </Animated.View>
          ) : (
            /* EMPTY STATE: Shown when no results are published in Atlas */
            <View style={styles.emptyContainer}>
              <View style={styles.emptyIconBg}>
                <Feather name="award" size={50} color="#cbd5e1" />
              </View>
              <Text style={styles.emptyTitle}>Results Not Published</Text>
              <Text style={styles.emptySub}>
                Your academic records will appear here once they are released by
                the school admin.
              </Text>
              <TouchableOpacity style={styles.refreshBtn} onPress={fetchResult}>
                <Ionicons name="refresh" size={20} color="#1e40af" />
                <Text style={styles.refreshTxt}>Check Again</Text>
              </TouchableOpacity>
            </View>
          )}

          <View style={{ height: 100 }} />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8fafc",
  },
  loadingTxt: {
    marginTop: 15,
    color: "#1e40af",
    fontWeight: "700",
    fontSize: 13,
  },

  // Background Ambient Light
  glowIndigo: {
    position: "absolute",
    top: -100,
    left: -50,
    width: 400,
    height: 400,
    borderRadius: 200,
    backgroundColor: "#eef2ff",
    opacity: 0.8,
  },
  glowPink: {
    position: "absolute",
    bottom: 50,
    right: -150,
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: "#fae8ff",
    opacity: 0.5,
  },

  scroll: { padding: 20 },

  // Summary Card
  summaryCard: {
    borderRadius: 35,
    padding: 25,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.8)",
    overflow: "hidden",
    elevation: 5,
  },
  termTxt: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    textAlign: "center",
    letterSpacing: 1.5,
  },
  scoreRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 25,
    justifyContent: "space-around",
  },
  scoreCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 4,
    borderColor: "#1e40af",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  percentTxt: { color: "#1e40af", fontSize: 24, fontWeight: "900" },
  labelTxt: {
    color: "#94a3b8",
    fontSize: 9,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  metaCol: { alignItems: "center" },
  gradeTxt: {
    color: "#1e293b",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 10,
  },
  statusBadge: {
    backgroundColor: "#10b981",
    paddingHorizontal: 15,
    paddingVertical: 6,
    borderRadius: 12,
  },
  statusTxt: { color: "#fff", fontSize: 10, fontWeight: "900" },

  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#1e293b",
    marginTop: 35,
    marginBottom: 15,
    textTransform: "uppercase",
    letterSpacing: 1,
  },

  // Subject Cards
  subjectCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    borderRadius: 28,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.7)",
    overflow: "hidden",
  },
  subIcon: {
    width: 45,
    height: 45,
    backgroundColor: "#fff",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
  },
  subInitial: { color: "#1e40af", fontSize: 18, fontWeight: "900" },
  subName: { fontSize: 15, fontWeight: "800", color: "#1e293b" },
  subMarks: { fontSize: 11, color: "#94a3b8", marginTop: 3, fontWeight: "700" },
  gradeBadge: {
    width: 38,
    height: 38,
    backgroundColor: "#eef2ff",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  itemGrade: { fontSize: 14, fontWeight: "900", color: "#1e40af" },

  // Action Button
  downloadBtn: {
    backgroundColor: "#1e293b",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    borderRadius: 22,
    marginTop: 25,
    elevation: 8,
  },
  downloadTxt: {
    color: "#fff",
    fontWeight: "900",
    marginLeft: 12,
    fontSize: 15,
  },

  // Empty State UI
  emptyContainer: {
    alignItems: "center",
    marginTop: 60,
    paddingHorizontal: 40,
  },
  emptyIconBg: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#1e293b",
    textAlign: "center",
  },
  emptySub: {
    fontSize: 13,
    color: "#94a3b8",
    textAlign: "center",
    marginTop: 10,
    lineHeight: 22,
    fontWeight: "600",
  },
  refreshBtn: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 25,
    backgroundColor: "#eef2ff",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 15,
  },
  refreshTxt: {
    marginLeft: 8,
    color: "#1e40af",
    fontWeight: "800",
    fontSize: 14,
  },
});

export default ResultScreen;
