import React, { useState, useEffect, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  FlatList,
  TouchableOpacity,
  ActivityIndicator,
  RefreshControl,
  StatusBar,
  Alert,
  Linking,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Feather } from "@expo/vector-icons";
import Animated, { FadeInUp } from "react-native-reanimated";
import { useAuth } from "../../context/AuthContext";
import apiClient from "../../api/apiClient";

const EarningsHub = () => {
  const { user } = useAuth();

  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [finance, setFinance] = useState({
    totalEarnings: 0,
    pendingEarnings: 0,
    invoices: [],
  });

  const fetchEarnings = useCallback(async () => {
    try {
      setLoading(true);
      const res = await apiClient.get(`/shop/earnings/${user.id}`);
      setFinance(res.data);
    } catch (err) {
      console.error("Finance Fetch Error:", err.message);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [user.id]);

  useEffect(() => {
    fetchEarnings();
  }, [fetchEarnings]);

  const onRefresh = () => {
    setRefreshing(true);
    fetchEarnings();
  };

  const handleDownload = async (url) => {
    if (!url)
      return Alert.alert(
        "Wait",
        "Invoice file is being generated by the system.",
      );

    const supported = await Linking.canOpenURL(url);
    if (supported) {
      await Linking.openURL(url);
    } else {
      Alert.alert("Error", "Could not open document link.");
    }
  };

  const settledCount = finance.invoices.filter(
    (i) => i.status === "Paid",
  ).length;

  const renderInvoice = ({ item, index }) => (
    <Animated.View entering={FadeInUp.delay(index * 30).duration(600)}>
      <View style={styles.invoiceCard}>
        <View style={styles.invoiceMain}>
          <View style={styles.invoiceInfo}>
            <Text style={styles.schoolName} numberOfLines={1}>
              {item.schoolName || "One-time Customer"}
            </Text>
            <Text style={styles.invoiceDate}>
              {new Date(item.createdAt).toLocaleDateString("en-GB", {
                day: "2-digit",
                month: "short",
                year: "numeric",
              })}
            </Text>
          </View>
          <View style={styles.invoiceAmount}>
            <Text style={styles.amountText}>
              ₹{item.amount.toLocaleString("en-IN")}
            </Text>
            <View
              style={[
                styles.statusBadge,
                {
                  backgroundColor:
                    item.status === "Paid" ? "#f5f5f5" : "#fff3e0",
                },
              ]}
            >
              <Text
                style={[
                  styles.statusText,
                  {
                    color: item.status === "Paid" ? "#000" : "#f57c00",
                  },
                ]}
              >
                {item.status}
              </Text>
            </View>
          </View>
        </View>
        <TouchableOpacity
          style={styles.downloadButton}
          onPress={() => handleDownload(item.pdfUrl)}
        >
          <Feather name="download" size={16} color="#000" />
        </TouchableOpacity>
      </View>
    </Animated.View>
  );

  return (
    <View style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#fff" />

      <SafeAreaView style={styles.safeArea} edges={["top"]}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.headerTitle}>Earnings</Text>
            <Text style={styles.headerSubtitle}>
              {finance.invoices.length}{" "}
              {finance.invoices.length === 1 ? "invoice" : "invoices"}
            </Text>
          </View>
          <TouchableOpacity style={styles.refreshButton} onPress={onRefresh}>
            <Feather name="refresh-cw" size={20} color="#000" />
          </TouchableOpacity>
        </View>

        {loading && !refreshing ? (
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color="#000" />
          </View>
        ) : (
          <FlatList
            data={finance.invoices}
            keyExtractor={(item) => item._id}
            renderItem={renderInvoice}
            showsVerticalScrollIndicator={false}
            refreshControl={
              <RefreshControl
                refreshing={refreshing}
                onRefresh={onRefresh}
                tintColor="#000"
              />
            }
            contentContainerStyle={styles.listContent}
            ListHeaderComponent={
              <View>
                {/* Revenue Summary */}
                <View style={styles.summaryCard}>
                  <View style={styles.summaryMain}>
                    <Text style={styles.summaryLabel}>Total Earnings</Text>
                    <Text style={styles.summaryValue}>
                      ₹{finance.totalEarnings.toLocaleString("en-IN")}
                    </Text>
                  </View>

                  <View style={styles.summaryDivider} />

                  <View style={styles.summaryStats}>
                    <View style={styles.statItem}>
                      <Text style={styles.statLabel}>Pending</Text>
                      <Text style={styles.statValue}>
                        ₹{finance.pendingEarnings.toLocaleString("en-IN")}
                      </Text>
                    </View>
                    <View style={styles.statDivider} />
                    <View style={styles.statItem}>
                      <Text style={styles.statLabel}>Settled</Text>
                      <Text style={styles.statValue}>{settledCount}</Text>
                    </View>
                  </View>
                </View>

                <Text style={styles.sectionTitle}>Invoice History</Text>
              </View>
            }
            ListEmptyComponent={
              <View style={styles.emptyState}>
                <Feather name="file-text" size={48} color="#e0e0e0" />
                <Text style={styles.emptyText}>No invoices yet</Text>
                <Text style={styles.emptySubtext}>
                  Your processed orders and receipts will appear here
                </Text>
              </View>
            }
          />
        )}

        {/* Create Invoice Button */}
        <TouchableOpacity
          style={styles.createButton}
          onPress={() =>
            Alert.alert("Feature", "New Invoice logic coming soon!")
          }
        >
          <Feather name="plus" size={24} color="#fff" />
        </TouchableOpacity>
      </SafeAreaView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  safeArea: {
    flex: 1,
  },

  // Header
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "600",
    color: "#000",
  },
  headerSubtitle: {
    fontSize: 13,
    color: "#666",
    marginTop: 2,
  },
  refreshButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f5f5f5",
    justifyContent: "center",
    alignItems: "center",
  },

  // List
  listContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 150,
  },

  // Summary Card
  summaryCard: {
    backgroundColor: "#f5f5f5",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  summaryMain: {
    marginBottom: 16,
  },
  summaryLabel: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
    marginBottom: 8,
  },
  summaryValue: {
    fontSize: 32,
    fontWeight: "600",
    color: "#000",
  },
  summaryDivider: {
    height: 1,
    backgroundColor: "#e0e0e0",
    marginBottom: 16,
  },
  summaryStats: {
    flexDirection: "row",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
  },
  statDivider: {
    width: 1,
    backgroundColor: "#e0e0e0",
  },
  statLabel: {
    fontSize: 11,
    color: "#999",
    fontWeight: "500",
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
  },

  // Section
  sectionTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#000",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // Invoice Card
  invoiceCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  invoiceMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  invoiceInfo: {
    flex: 1,
    marginRight: 12,
  },
  schoolName: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000",
    marginBottom: 4,
  },
  invoiceDate: {
    fontSize: 12,
    color: "#666",
  },
  invoiceAmount: {
    alignItems: "flex-end",
  },
  amountText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#000",
    marginBottom: 4,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 10,
    fontWeight: "600",
  },
  downloadButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
  },

  // Create Button
  createButton: {
    position: "absolute",
    bottom: 100,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },

  // Loading
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },

  // Empty State
  emptyState: {
    alignItems: "center",
    paddingTop: 80,
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#000",
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 13,
    color: "#666",
    marginTop: 4,
    textAlign: "center",
    lineHeight: 20,
  },
});

export default EarningsHub;
